### ISSUE TITLE
2021.1.19提问，求答，谢谢！

### ISSUE THREAD

**Issue by KaneTheo** [jinmu333/Lenovo_G40_70M_EFI#2]
这个efi 可以用在黑果小兵最新的macOS BigSur 11.1 20C69 正式版 with Clover 5127原版镜像。吗？
小白一个，第一次安装黒果，求解答，谢谢！
（姐姐大学退下来的旧电脑，win用着比较卡，想让它焕发第二春🤗）

**Comment by xx12138123** [comment]
> 这个efi 可以用在黑果小兵最新的macOS BigSur 11.1 20C69 正式版 with Clover 5127原版镜像。吗？
> 小白一个，第一次安装黒果，求解答，谢谢！
> （姐姐大学退下来的旧电脑，win用着比较卡，想让它焕发第二春🤗）

不如试一下精简版的win10，换一个固态

**Comment by KaneTheo** [comment]
>
